### ISSUE TITLE
Add interactive gallery of traces

### ISSUE THREAD

**Issue by greghutch** [googlemaps/fleet-debugger#53]
1) Demos should be runnable locally
2) Demo traces should/could be data used in future tests
3) Expose this gallery via jsfiddle in developers.google.com documentation.  See https://docs.jsfiddle.net/github-integration/untitled-1

**Comment by bshi** [comment]
What is a "trace" in this context?

**Comment by greghutch** [comment]
fixed by https://github.com/googlemaps/fleet-debugger/commit/436b3792a8e6cdfeaac3b9cbd56fb16330b5dfc2
