### ISSUE TITLE
Visualize delta between servertime and rawLocationTime

### ISSUE THREAD

**Issue by greghutch** [googlemaps/fleet-debugger#77]
rawLocationTime is the time at which the GPS measurement was recorded (on device).   A large delta could indicate connectivity issues or app bugs.

**Comment by bshi** [comment]
IIRC we also track client timestamp at time of log entry creation/emission right?  Might be more reliable to use the delta between client log ts & rawLocationTime rather than derive a value from two values measured from server & client.

**Comment by greghutch** [comment]
Hmm.  Agree that a delta between two client times would be more consistent.  But which field is the client time?  We have 'timestamp', 'receiveTimestamp' and rawLocationTime in the logs.   I'm not actually sure of the source of each.   Is this correct:
  - timestamp = device timestamp (or is it the time our backend got the request?)
  - receiveTimestamp = server timestamp (or is it the cloud logging timestamp)
  - rawLocationTime = device time at which a location measurement was taken

**Comment by bshi** [comment]
I might've misremembered.  Looks like timestamp is measured from FE perspective.  receiveTimestamp tracks when it was ingested by centralized logging.  I'll follow up on whether there's any emit timestamp measured from client.
